---
- name: Add Docker GPG key.
  become: yes
  apt_key: "url={{ docker_apt_key }}"

- name: Add Docker APT repository.
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Install docker and its dependencies.
  become: yes
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'gnupg-agent'
    - 'software-properties-common'
    - "{{ docker_package }}"
    - python-docker

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: docker
    state: "started"
    enabled: "true"

- name: Allow user to start containers.
  become: yes
  command: "usermod -aG docker {{ docker_user }}"